server:
  port: 9190
  
spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ram-chadar/ms-config
          clone-on-start: true  
    
